### ISSUE TITLE
Is gatsby missing in the main branch?

### ISSUE THREAD

**Issue by Otann** [friends-of-fiskaly/antrag-148AO-wizard-tool#21]
Hello @StefanKohlbacher !
Amazing that you did this simple thing and that we can deploy it on our gh-pages.

I work at iZettle and Johannes told me I can reach out if I have questions or problems.
I see in the readme that you run it with Gatsby and I see in the `gh-pages` traces of Gatsby too.

However, I don't see it in the `package.json`. I am mostly backender with only some experience of frontend, maybe I am missing some local setup? Could you help?

**Comment by Otann** [comment]
🤦  found the `/webpage` subfolder

**Comment by StefanKohlbacher** [comment]
Hello @Otann , 
sorry for the late answer. 
I guess you would like to host the webpage yourself, rather then implement the component into one of your existing pages. Is this correct? If there are any further questions with that, I am happy to help! It might even be easier to jump in a quick call to resolve any issues.
